name: Cron Schedule Test
on:
  schedule:
    - cron: '12 11 * * *'  # 7:12 PM PHT (Next hour)
    - cron: '37 11 * * *'  # 7:37 PM PHT
    - cron: '53 11 * * *'  # 7:53 PM PHT
  workflow_dispatch:

jobs:
  test-schedule:
    runs-on: ubuntu-latest
    steps:
      - name: System Check
        run: |
          echo "The cron job successfully triggered!"
          echo "Current UTC time: $(date -u)"
          echo "Current PHT time: $(date)"
